language: cpp
os: linux
dist: trusty
sudo: required
compiler:
  - g++
  #- clang++

branches:
  only:
    - master
    - coveralls
    - travis
    - ref-rel

git:
  depth: 1
  # handle git submodules manually
  submodules: false

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq --yes update
  # handle git submodules manually
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install: 
  - gem install coveralls-lcov
  #- sudo apt-get install --yes cmake cmake-data
  - sudo apt purge cmake
  - sudo apt-get install --yes libboost-all-dev
  - sudo apt-get install --yes lcov

before_script:
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # cmake (3.10.2)
  - cd $PARENT_DIR
  - wget https://cmake.org/files/v3.10/cmake-3.10.2.tar.gz
  - tar zxvf cmake-3.10.2.tar.gz
  - cd cmake-3.10.2
  - ./bootstrap
  - make && sudo make install
  - cmake --version
  # z3 (4.8.1)
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout b301a59899ff401dc1a98dd522b8a8df19471dee
  - python scripts/mk_make.py
  - cd build
  - make && sudo make install
  - z3 --version
  # glog
  - cd $PARENT_DIR
  - git clone --depth 1 https://github.com/google/glog.git
  - mkdir -p $PARENT_DIR/glog/build/
  - cd $PARENT_DIR/glog/build/ 
  - cmake ..
  - make && sudo make install
  # coverage test
  - lcov --version
  - gcov --version
  - g++ --version
  # create Makefile
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -L -DZ3_INCLUDE_DIR=/usr/include -Dglog_DIR=$PARENT_DIR/glog/build -Dcoverage=ON -Dpython-api=ON -Dverilog-in=ON -Djson-inout=ON -Ddebug=ON $TRAVIS_BUILD_DIR
  - make && sudo make install

after_success:
  - make run_test
  - lcov --directory $TRAVIS_BUILD_DIR/build --capture --output-file coverage.info 
  - lcov --remove coverage.info 'glog/*' 'test/*' 'app/*' 'cmake/*' '/usr/*' 'src/verilog-in/byh-verilog-parser/*' 'src/json-inout/nlohmann-json/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - coveralls-lcov coverage.info 

notifications:
    email: false
