language: cpp
compiler: gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install libboost-all-dev
    
install: 
    - mkdir cbuild
    - cd cbuild
    - cmake ../ -L -DZ3_INCLUDE_DIR=/usr/include
    - make -j
