language: cpp
compiler: gcc

branches:
    only:
    - travisBranch

os:
    - linux

env:
    - SH=bash

git:
    depth: 3

before_install:
    # boost
#- until sudo apt-get -qq update; do echo retry; done
#- sudo apt-get --yes update
#- sudo apt-get install --yes libboost-all-dev
    # z3
#- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu wily main universe" -y
#- sudo apt-get autoremove -f
#- sudo apt-get install -f
#- sudo apt-get update -q
#- sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
#- sudo apt-get install -f -q z3 -y
    
install: 
#- until sudo apt-get -qq install libboost-all-dev libboost-test-dev libboost-program-options-dev; do echo retry; done

before_script:
    # boost
    - wget --no-verbose --output-document=boost-trunk.tar.gz https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz/download
    - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
    - mkdir -p $BOOST_ROOT
    - tar -zxf boost-trunk.tar.gz -C $BOOST_ROOT
    - cd $BOOST_ROOT
    - echo $BOOST_ROOT
    - ls
    - ./bootstrap.sh --prefix=$BOOST_ROOT
    - sudo ./b2 install
    - export PATH=$BOOST_ROOT/:$PATH
    - export C_INCLUDE_PATH=$BOOST_ROOT/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=$BOOST_ROOT/:$CPLUS_INCLUDE_PATH
    - export BOOST_BUILD_PATH=$BOOST_ROOT
    - cd $TRAVIS_BUILD_DIR
    # z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - python scripts/mk_make.py
    - cd build
    - make
    - sudo make install
    - cd $TRAVIS_BUILD_DIR

script:
    - bjam --version
    - which bjam
    - ls /usr/bin/z3
    - /usr/bin/z3 --version
    - cd synthesis/libcpp
    - bjam

notifications:
    email: false
#slack:
#on_success: never
#on_failure: never
