language: cpp

branches:
    only:
    - travisBranch

os:
    - linux

env:
    - SH=bash

git:
    depth: 3

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq -y update
    
install: 
    - sudo apt-get -qq -y install g++-4.8
    - sudo apt-get -qq install libstdc++-4.8-dev

before_script:
    # boost
    - wget --no-verbose --output-document=boost-trunk.tar.gz https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz/download
    - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
    - mkdir -p $BOOST_ROOT
    - tar -zxf boost-trunk.tar.gz --strip-components=1 -C $BOOST_ROOT > /dev/null
    - cd $BOOST_ROOT
    - ./bootstrap.sh --prefix=$BOOST_ROOT > /dev/null
    - ./b2 
    - ./b2 install 
    - export PATH=$BOOST_ROOT/:$PATH
    - export C_INCLUDE_PATH=$BOOST_ROOT/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=$BOOST_ROOT/:$CPLUS_INCLUDE_PATH
    - export BOOST_BUILD_PATH=$BOOST_ROOT
    - cd $TRAVIS_BUILD_DIR
    # z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - python scripts/mk_make.py
    - cd build
    - make 
    - sudo make install
    - cd $TRAVIS_BUILD_DIR

script:
    - cd synthesis/libcpp
    - mkdir -p cbuild
    - cd cbuild
    - cmake ../ -L -DZ3_INCLUDE_DIR=/usr/include
#- bjam

notifications:
    email: false
#slack:
#on_success: never
#on_failure: never
