os: linux
dist: xenial
sudo: required
language: cpp
compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - travis

git:
  submodules: false

before_install:
  - gem install coveralls-lcov

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev

install: 
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # z3 
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
    #- python scripts/mk_make.py
    #- if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then python scripts/mk_make.py ; fi
    #- if [[ "$TRAVIS_COMPILER" == "clang" ]]; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
    #- cd build
  - mkdir -p build
  - cd build
  - cmake .. 
  - make && sudo make install
  - z3 --version

before_script:
  - cmake --version
  - lcov --version
  - gcov --version

script:
  - mkdir -p $TRAVIS_BUILD_DIR/build 
  - cd $TRAVIS_BUILD_DIR/build
  - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make 
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

after_success:
  - lcov --directory $TRAVIS_BUILD_DIR/build --capture --output-file coverage.info 
  - lcov --remove coverage.info '*/extern/*' '*/test/*' '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - coveralls-lcov coverage.info 

notifications:
    email: false

