language: cpp
os: linux
sudo: required
dist: trusty

branches:
  only:
    - master
    - coverity_check
    - travis

git:
  depth: 1

env:
  global:
    - secure: "XNtJYTfzrD85b7b4ul6OVaw0UMRz5OoGQOFlDeBvpKSLhfjQ8ci6PpDiHsXsxsPJYpxHHpU6hMJSd/QVX4Ux5qd7SaDRigL8FO38XqrNrgHKWElmpfiYbI1OCXJWNbIwABXhMKSOFgsbMkKdQi5qLevCKwQWc1Kv+hODm0CIK/gmizX010egHs5olydSlHegvWz23anSYh7JBqBE2BWMACoPjl3ZmTPvP05og0FvtfEzE4FaSOgWpjarBayF/p2chHBlRhsytJ1bSdVlQTQaArwPkJr1AMxWmzzZ99h6yUetATXSr4JoXhuDyrEYO3f1I/m/nq4FaLZdka9BYOXprQ6RH5nsnonqb2HwinLKq5guHkq/HTMJkhuL0pb210U+tj9x4DuUMLBCM06p/46ZEyVrAqcllyfn4+Lmhj0tVjnC1/+5XNk7FRK0dNb+2lEQTW/KShTMD/1scu/b8keSVV6gSBDHG3OhbiYqMF9pd1gJILCsk0CUj1Br1+3yTh/CicDZ4meTixi0glefCnsTG8XftI0XM5W8rUJ/Hpz1ygCnXNcbAW+36uXICp8kmyWGSISf6AQwvr2DwB5AYW66pYXn57ZKCxpzkEHxYACXRs6Fvn/1cr/WK9H64IVmPvBkBpp8xa+FH2ZWsMhOAglqASISixQmT1emB7cxGZc5Bdk="

addons:
  coverity_scan:
    project:
      name: "Bo-Yuan-Huang/ILA-Tools"
      description: "ILA build submitted via Travis CI"
    notification_email: byhuang1992@gmail.com
    build_command_prepend: "cmake -Dcoverage=ON -DZ3_INCLUDE_DIR=/usr/include $PARENT_DIR"
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq --yes update

install: 
  - gem install coveralls-lcov
  - sudo apt-get install --yes cmake cmake-data
  #- sudo apt-get install --yes libboost-dev
  - sudo apt-get install --yes lcov

before_script:
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # boost
  #- wget --output-document=boost-trunk.tar https://www.dropbox.com/s/mub9p5wl1td6r8y/boost_1_61_0.tar?dl=0
  #- export BOOST_ROOT="$PARENT_DIR/boost-trunk"
  #- mkdir -p $BOOST_ROOT
  #- tar -xvf boost-trunk.tar --strip-components=1 -C $BOOST_ROOT > /dev/null
  #- cd $BOOST_ROOT
  #- ./bootstrap.sh
  #- ./b2 
  #- sudo ./b2 install 
  #- export BOOST_ROOT=$BOOST_ROOT
  #- alias bjam=$BOOST_ROOT/bjam
  #- export C_INCLUDE_PATH=$BOOST_ROOT/:$C_INCLUDE_PATH
  #- export CPLUS_INCLUDE_PATH=$BOOST_ROOT/:$CPLUS_INCLUDE_PATH
  #- export C_INCLUDE_PATH=/usr/include/:$C_INCLUDE_PATH
  #- export CPLUS_INCLUDE_PATH=/usr/include/:$CPLUS_INCLUDE_PATH
  #- export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
  #- export CPLUS_INCLUDE_PATH=/usr/local/include/:$CPLUS_INCLUDE_PATH
  #- export BOOST_BUILD_PATH=$BOOST_ROOT
  #- export LIBRARY_PATH=$BOOST_ROOT/stage/lib/:$LIBRARY_PATH
  #- export LD_LIBRARY_PATH=$BOOST_ROOT/stage/lib/:$LD_LIBRARY_PATH
  - cd $PARENT_DIR
  # z3
  #- git clone --depth 1 https://github.com/Z3Prover/z3.git
  #- cd z3
  #- python scripts/mk_make.py
  #- cd build
  #- make; sudo make install
  # glog
  - cd $PARENT_DIR
  - git clone https://github.com/google/glog.git
  - mkdir -p $PARENT_DIR/glog/build/
  - cd $PARENT_DIR/glog/build/ 
  - cmake ..
  - make && sudo make install
  # coverage test
  - lcov --version
  - gcov --version
  - g++ --version
  # create Makefile
  - mkdir -p $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - lcov --directory $TRAVIS_BUILD_DIR/build --zerocounters

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake -L -DZ3_INCLUDE_DIR=/usr/include -Dglog_DIR=$PARENT_DIR/glog/build -Dcoverage=ON -Dpython_api=OFF $TRAVIS_BUILD_DIR
  - make

after_success:
  - make run_test
  - lcov --directory $TRAVIS_BUILD_DIR/build --capture --output-file coverage.info 
  - lcov --remove coverage.info 'test/*' 'app/*' 'external/*' 'cmake/*' '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - coveralls-lcov coverage.info 

notifications:
    email: false
