language: cpp

branches:
    only:
    - travisBranch
    - master

os:
    - linux

env:
    matrix:
        - CMAKE_CXX_COMPILER=g++-4.8

#git:
#    depth: 3

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qq --yes update
    - sudo apt-add-repository --yes ppa:smspillaz/cmake-2.8.12
    - sudo apt-get -qq --yes update
    
install: 
    - sudo apt-get install --yes cmake cmake-data
    - sudo apt-get -qq --yes update
    - sudo apt-get install --yes libgmp-dev
    - sudo apt-get -qq --yes update
    - sudo apt-get install --yes -qq g++-4.8
    - sudo apt-get -qq --yes update
    - sudo apt-get install --yes -qq libstdc++-4.8-dev

before_script:
    # boost
    - wget --no-verbose --output-document=boost-trunk.tar.gz https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz/download
    - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
    - mkdir -p $BOOST_ROOT
    - tar -zxf boost-trunk.tar.gz --strip-components=1 -C $BOOST_ROOT > /dev/null
    - cd $BOOST_ROOT
    - ./bootstrap.sh 
    - ./b2 
    - sudo ./b2 install 
    - export BOOST_ROOT=$BOOST_ROOT
    - alias bjam=$BOOST_ROOT/bjam
    - export C_INCLUDE_PATH=$BOOST_ROOT/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=$BOOST_ROOT/:$CPLUS_INCLUDE_PATH
    - export C_INCLUDE_PATH=/usr/include/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=/usr/include/:$CPLUS_INCLUDE_PATH
    - export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
    - export CPLUS_INCLUDE_PATH=/usr/local/include/:$CPLUS_INCLUDE_PATH
    - export BOOST_BUILD_PATH=$BOOST_ROOT
    - export LIBRARY_PATH=$BOOST_ROOT/stage/lib/:$LIBRARY_PATH
    - export LD_LIBRARY_PATH=$BOOST_ROOT/stage/lib/:$LD_LIBRARY_PATH
    - cd $TRAVIS_BUILD_DIR
    # z3
    - git clone https://github.com/Z3Prover/z3.git
    - cd z3
    - git checkout bd0bd6052a9e52712326f680f2b7415a93c4d1e0
    - python scripts/mk_make.py
    - cd build
    - make 
    - sudo make install
    - cd $TRAVIS_BUILD_DIR

script:
    - cd $TRAVIS_BUILD_DIR/synthesis/libcpp
    - $BOOST_ROOT/bjam
    - mkdir -p cbuild
    - cd cbuild
    - cmake ../ -L -DZ3_INCLUDE_DIR=/usr/include
    - cmake --build .

notifications:
    email: false
#slack:
#on_success: never
#on_failure: never
