branches:
  only:
    - master
    - travis

git:
  depth: 1
  submodules: false

language: cpp

matrix:
  include:
    - name: "linux-gcc"
      os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - gem install coveralls-lcov
      before_script:
        - mkdir -p $TRAVIS_BUILD_DIR/build 
        - source $TRAVIS_BUILD_DIR/scripts/clean-coverage.sh $TRAVIS_BUILD_DIR/build
      after_success:
        - source $TRAVIS_BUILD_DIR/scripts/submit-coverage.sh $TRAVIS_BUILD_DIR/build

    - name: "linux-clang"
      os: linux
      dist: xenial
      compiler: clang

    - name: "trusty49"
      os: linux
      dist: trusty
      addons:
        apt: 
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
        - eval "${MATRIX_EVAL}"

    - name: "osx"
      os: osx
      before_install:
        - brew install bison
        - export PATH="/usr/local/opt/bison/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/bison/lib"

sudo: required

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev
  homebrew:
    update: true
    packages:
      - flex
      - python
      - boost
      - boost-python

install: 
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # z3 
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  - python scripts/mk_make.py
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then python scripts/mk_make.py ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - make && sudo make install
  - z3 --version

script:
  - mkdir -p $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make 
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

notifications:
    email: false
