language: cpp

matrix:
  include:
    - name: "linux gcc"
      os: linux
      dist: xenial
      compiler: gcc
    - name: "linux clang"
      os: linux
      dist: xenial
      compiler: clang
    - name: "osx gcc"
      os: osx
      compiler: gcc
    - name: "osx clang"
      compiler: clang

sudo: required

branches:
  only:
    - master
    - travis

git:
  submodules: false

before_install:
  - gem install coveralls-lcov

addons:
  apt:
    update: true
    packages:
      - lcov
      - flex
      - bison
      - libboost-all-dev

install: 
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # z3 
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
  - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  - python scripts/mk_make.py
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then python scripts/mk_make.py ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - make && sudo make install
  - z3 --version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" -a "$TRAVIS_COMPILER" == "gcc" ]]; then export SUBMIT_COVERAGE=true ; fi
  - chmod ugo+x scripts/clean-coverage.sh
  - chmod ugo+x scripts/submit-coverage.sh
  - mkdir -p $TRAVIS_BUILD_DIR/build 
  - if [[ "$SUBMIT_COVERAGE" == "true" ]]; then ./scripts/clean-coverage.sh $TRAVIS_BUILD_DIR/build ; fi

script:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake .. -DILANG_BUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug
  - make 
  - sudo make install
  - make run_test
  - ctest -R ExampleCMakeBuild

after_success:
  - if [[ "$SUBMIT_COVERAGE" == "true" ]]; then ./scripts/submit-coverage.sh $TRAVIS_BUILD_DIR/build ; fi

notifications:
    email: false

