language: cpp
compiler: gcc

branches:
    only:
    - travisBranch

os:
    - linux

env:
    - SH=bash

git:
    depth: 3

before_install:
    # boost
    - until sudo apt-get -qq update; do echo retry; done
    - sudo apt-get --yes update
    - sudo apt-get install --yes libboost-all-dev
    # z3
#- sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu wily main universe" -y
#- sudo apt-get autoremove -f
#- sudo apt-get install -f
#- sudo apt-get update -q
#- sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
#- sudo apt-get install -f -q z3 -y
    
install: 
    - until sudo apt-get -qq install libboost-all-dev libboost-test-dev libboost-program-options-dev; do echo retry; done

before_script:
    # boost
    - wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz/download
    - tar -zxf download
    - cd boost_1_63_0
    - ./bootstrap.sh --prefix=/usr/
    - ./b2
    - sudo ./b2 install
    # z3
#- git clone https://github.com/Z3Prover/z3.git
#- cd z3
#- python scripts/mk_make.py
#- cd build
#- make
#- sudo make install
#- cd ../

script:
    - bjam --version
    - which bjam
    #- ls /usr/bin/z3
    #- /usr/bin/z3 --version
    #- cd synthesis/libcpp
    #- bjam

notifications:
    email: false
#slack:
#on_success: never
#on_failure: never
